### ISSUE TITLE
直接setPercent(100)会出现数据有误的BUG

### ISSUE THREAD

**Issue by zzsakurazz** [SuperKung/DashboardView#3]
在xml中设置`app:maxNumber="100"`
当我直接设值`setPercent(100)`的时候，一边数字就会出现显示“101.0”
但当我
`if (i < 100) {
                    i = i + 20;
                } else if (i == 100) {
                    i = 1;
                }
                dashboardView.setPercent(i);`时却不会出现此问题
应该是在计算的时候的问题，望能修复次BUG

**Comment by zzsakurazz** [comment]
我又看了一下，应该是插值器的问题XD

**Comment by SuperKung** [comment]
@zzsakurazz 好久没看这个东西了，解决了吗？不行的话可以换个插值器

**Comment by zzsakurazz** [comment]
我自定义了一个插值器，已经解决了XD
