### ISSUE TITLE
数值只能setPercent,必须是int吗？

### ISSUE THREAD

**Issue by realchen** [SuperKung/DashboardView#6]
这个可以支持float吗？
可以分段显示颜色吗

**Comment by SuperKung** [comment]
float 可以转成int，或者用round函数四舍五入一下，颜色是个渐变效果，只能设置开始和结束的颜色，如果有需求可以自己把代码下载下来自己改一下渐变那块的代码
________________________________
发件人: realchen <notifications@github.com>
发送时间: 2018年10月9日 5:34
收件人: SuperKung/DashboardView
抄送: Subscribed
主题: [SuperKung/DashboardView] 数值只能setPercent,必须是int吗？ (#6)


这个可以支持float吗？
可以分段显示颜色吗

―

**Comment by realchen** [comment]
好的 了解了
